language: go
go:
  - '1.12'
install:
  - make tools
script:
  - make test
before_deploy:
  - make build-x
deploy:
  provider: releases
  api_key:
    secure: EcVTTjd6cMShA+1L2j2/gQCAJ/9uGlG0Isnwk/9EhtXPoDI2yoQMSh2N8O8ws4rGSC3mXxrJZ8z12w7Uk8NVZg4HtzES1lk0VT00wJDzxHvA40AQVTq1XphnC7PyFIxWFHvyruysj4KOs989AUNJ1UVbemkmtBd5qRLxQoC+8OwED25XR+rVJLq9+4AlqrnnZYkoyCcnx+9ZsDqL691iEeOWgS0S2dIGKalaypv4jmPwRj7QGjoWysmN7w18WsZjkTs/HfpIU24ZPbiabvpNeMQTFV/YBFiA9fzTxZE/choUI4l3+YshXxw5beyX1BLMzpOck8DG0BFy4b6G4VuIG0r16zKVgdCSS5n067Ern9C+hgPBYf4LJKpmys9a6CSfXmFOninGE5Yu49zEkQtjaTG8S4AIUVYxdaLp3n3c6xDTnCLtVHvckLL7/pm4p6UMJzTM056RwzCD7zn9+em+8iQWD5emQO9OA++DOaPywViY0G602gXmZuRDR3oC0Lgw3rhHTYKQpbPnI3C7wklGVZOmvtbEQNR2bSZJWT2TdFFq0ZimYH560eXdYkgJr7nOBTKL8z5QmjUs49GRkKIpn2Qt+uf/LoqhF53XCoBTzdXOkH4Qd0tOF1oSR5/V8VJP2yn1h38nTmeIcuyqZV+XSCmoSf2SU/GWsTx4XOu9I/Q=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  name: "$TRAVIS_TAG"
  on:
    tags: true
    repo: yamamoto-febc/terraform-provisioner-vnc
